before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w
  main: ./cmd/discord-slowmode-bot/main.go
archives:
- replacements:
  darwin: Darwin
  linux: Linux
  windows: Windows
  386: i386
  amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
